SERVERS =
[
  {
   :BOX_NAME => 'centos/7',
   :HOSTNAME => 'rpms',
   :IP => '192.168.56.10',
   :RAM => 1024,
   :CPU => '1'
  }
]

# Конфигурация Vagrant версии 2
Vagrant.configure('2') do |config|
 # Проходим по элементах массива SERVERS
 SERVERS.each do |machine|
   # Применяем конфигурации для каждой машины
   config.vm.define machine[:HOSTNAME] do |node|
     # Создаем box
     node.vm.box = machine[:BOX_NAME]
     # Hostname который будет присвоен VM (самой ОС)
     node.vm.hostname = machine[:HOSTNAME]
     # Добавление и настройка внутреннего сетевого адаптера
     node.vm.network 'private_network', ip: machine[:IP]
     # Тонкие настройки (VirtualBox)
     node.vm.provider :virtualbox do |vb|
       # Размер RAM памяти
       vb.customize ['modifyvm', :id, '--memory', machine[:RAM]]
       # Количество CPU
       vb.customize ['modifyvm', :id, '--cpus', machine[:CPU]]
       # Название VM
       vb.name = machine[:HOSTNAME]
     end
     # Настройки SSH
     node.vm.provision "shell", inline: <<-SHELL
       mkdir -p ~root/.ssh
       cp ~vagrant/.ssh/auth* ~root/.ssh
       sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/openssh/sshd_config
       systemctl restart sshd
     SHELL
   end
 end
end