# Описываем Виртуальные машины
servers = {
        # Указываем имя ВМ "HW2v2"
        :"HW2v2" => {
                #Какой vm box будем использовать
                :box_name => "generic/centos9s",
                #Указываем box_version
                :box_version => "4.3.12 ",
                #Указываем количество ядер ВМ
                :cpus => 2,
                #Указываем количество ОЗУ в мегабайтах
                :memory => 2048,
        }
}

# Конфигурация Vagrant версии 2
Vagrant.configure("2") do |config|
        servers.each do |boxname, boxconfig|
                # Отключаем проброс общей папки в ВМ
                config.vm.synced_folder ".", "/vagrant", disabled: true
                # Применяем конфигурацию ВМ
                config.vm.define boxname do |box|
                        box.vm.box = boxconfig[:box_name]
                        box.vm.box_version = boxconfig[:box_version]
                        box.vm.host_name = boxname.to_s
                        box.vm.provider "virtualbox" do |v|
                                v.cpus = boxconfig[:cpus]
                                v.memory = boxconfig[:memory]
                        end

		config.vm.provision "shell", inline: <<-SHELL
			sudo yum update -y
			sudo yum install https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm -y
			sudo yum --enablerepo elrepo-kernel install kernel-ml -y
			sudo grub2-mkconfig -o /boot/grub2/grub.cfg
			sudo reboot
		SHELL

                end
        end
end
